language: cpp

dist: trusty

compiler:
  - clang
  - gcc

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required
      - os: osx
        osx_image: xcode8.2

addons:
  apt:
    packages:
      - libsdl2-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev
      - libosmesa6-dev
      - libboost-regex-dev
      - libglm-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then bash tci_osx_setup.sh; fi

git:
    submodules: true

branches:
    only:
        - master
        - lsdraw_0.1.x

before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - cmake .. -G"Unix Makefiles"

script:
    make
