language: cpp



os:
  - osx
  - linux



compiler:
  - gcc
  - clang



dist: trusty
osx_image: xcode8.2
sudo: required



addons:
    apt:
        packages:
          - libsdl2-dev
          - libfreeimage-dev
          - libassimp-dev
          - libfreetype6-dev
          - libosmesa6-dev
          - libboost-regex-dev
          - libglm-dev



before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash tci_osx_setup.bash; fi



git:
    submodules: true



branches:
    only:
      - master
      - lsdraw_0.1.x



before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - cmake .. -G"Unix Makefiles"



script:
    make

