language: cpp



os:
  - osx
  - linux



compiler:
  - gcc
  - clang



dist: trusty
osx_image: xcode8.2
sudo: required



addons:
    apt:
        packages:
          - mercurial
          - libosmesa6-dev



git:
    submodules: true



branches:
    only:
      - master



before_script:
  - git checkout master
  - git submodule init
  - git submodule foreach git checkout master
  - mkdir build
  - cd build
  - cmake .. -G"Unix Makefiles"



script:
    make

